name: Eiger
description: Eiger

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_easyloading: ^3.0.5
  intl: ^0.17.0
  shimmer: ^2.0.0
  dio: ^4.0.6
  flutter_bloc: ^8.1.1
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^6.0.0
  pull_to_refresh: ^2.0.0
  flutter_svg: ^1.1.5
  smooth_page_indicator: ^1.0.0+2
  flutter_animation_progress_bar: ^2.3.1
  flutter_datetime_picker: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/icons/
    - assets/images/backgrounds/
    - lib/dummy/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
